---
name: KM-BB
description: Medium like.
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
email: test@gmail.com
mailchimp-list: ''
include:
- _pages
permalink: "/:title/"
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
authors:
  sal:
    name: KM Ashmil
    site: https://ashmil.me
    avatar: "/assets/images/avatar1.jpg"
    bio: Hi, I am KM, I hope you like it!
    email: ''
    twitter: https://twitter.com/
  jane:
    name: Jane
    site: https://www.wowthemes.net
    avatar: "/assets/images/avatar2.jpg"
    bio: Blogger, fashionista, love to explore new ideas and write on my morning coffee!
    email: fakemail@gmail.com
    twitter: https://twitter.com/wowthemesnet
defaults:
- scope: ''
  values: ''
- scope:
    path: _posts
  values:
    layout: post
    author: sal
    avatar: "/assets/images/avatar1.jpg"
paginate: "10"
